### 매우 주요

1. 문자열 값을 허용하지 않음 따라서 모든 문자열 값은 인코딩해서 숫자로 변환 필수

2. 문자열인 경우 카테고리형(코드로 변환 권장) / 텍스트 피처(백터화 권장)

3. 데이터 인코딩 : 레이블 인코딩(카테고리형을 코드형 숫자화)/원핫 인코딩(주요 index의 값만 1, 나머지는 0값)

<hr>

**레이블 인코딩**

문자열을 숫자로 변환 

In [3]:
from sklearn.preprocessing import LabelEncoder

items = ['하나', '둘', '셋', '넷', '오']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print(labels)

[4 1 2 0 3]


In [4]:
print(encoder.classes_)

['넷' '둘' '셋' '오' '하나']


In [8]:
print('복원 : 디코딩 - ', encoder.inverse_transform([4, 1, 2, 0 ,3]))

복원 : 디코딩 -  ['하나' '둘' '셋' '넷' '오']


<hr>

**원-핫 인코딩(One-Hot Encoding)**

1. feature값 유형에 따라 가령 새로운 피처가 추가될 경우에 해당 컬럼에만 1값 적용, 나머지는 0으로 채움  <br>
2. 작업 단계 : 숫자값으로 변환(LabelEncoder) -> 2차원 데이터 구조로 변경(reshape) -> 원핫 인코딩 적용

In [16]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['하나', '둘', '셋', '넷', '오']
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

# 원-핫 인코딩 적용
one_encoder = OneHotEncoder()

# 2차원 데이터 구조로 변환
labels = labels.reshape(-1, 1)

# print(labels)
one_encoder.fit(labels)
one_labels = one_encoder.transform(labels)
print(one_labels)

print(one_labels.toarray())

  (0, 4)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 0)	1.0
  (4, 3)	1.0
[[0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]]


**문자열 카테고리 값을 숫자형으로 변환하는 번잡스러움 없이 바로 변환 가능**

In [18]:
import pandas as pd

In [19]:
df = pd.DataFrame({'items' :['하나', '둘', '셋', '넷', '오']})

In [21]:
pd.get_dummies(df)

items_넷  items_둘  items_셋  items_오  items_하나
0        0        0        0        0         1
1        0        1        0        0         0
2        0        0        1        0         0
3        1        0        0        0         0
4        0        0        0        1         0